name: GoREST Node.js API Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run API tests (Create User)
        run: node tests/1_createUser.js

      - name: Run API tests (Get User)
        run: node tests/2_getUser.js

      - name: Run API tests (Update User)
        run: node tests/3_updateUser.js

      - name: Run API tests (Delete User)
        run: node tests/4_deleteUser.js

      - name: Run API tests (Negative test)
        run: node tests/5_updateUser_no_token.js